---
output:
  md_document:
    variant: markdown_github
---

## Homework 9 Links

Since this is the READEME of the github folder containing the powers package scripts and info, here are the links where you can find all the necessary files!

* Folder with [R scripts](https://github.com/vanflad/STAT547-hw-fladmark-vanessa/tree/master/Homework%209/R) for functions
* The powers package [vignette](https://github.com/vanflad/STAT547-hw-fladmark-vanessa/blob/master/Homework%209/inst/doc/my_vignette.Rmd)
* [Description](https://github.com/vanflad/STAT547-hw-fladmark-vanessa/blob/master/Homework%209/DESCRIPTION), [Namespace](https://github.com/vanflad/STAT547-hw-fladmark-vanessa/blob/master/Homework%209/NAMESPACE) and [License]() in case you want to see those
* Homework [instructions](http://stat545.com/hw09_package.html) from STAT545/547 website
* Link to Vincenzo's github with some [powers package](https://github.com/vincenzocoia/powers/blob/master/R/pow.R) details that helped get me started
* Couldn't get the [package to download from Github](https://stackoverflow.com/questions/31424883/how-do-i-install-rhadoop-package-rhdfs-from-github-using-devtools) and I realized the link given inside `devtools::install_github()` has to be given in a very specific format using `subdir = "Homework 9/Powers"` as I discovered from Stack Overflow!!

## Powers

In order to download my package, use the following code to install (then don't forget to load `library(Powers)` afterwards)!

```{r}
devtools::install_github("vanflad/STAT547-hw-fladmark-vanessa", subdir = "Homework 9/Powers")
```

The goal of powers is to calculate the exponential power of a number! There are a variety of functions to choose from, such as `square()`, `cube()`, `reciprocal()` and `pow()` for calculating to the power of two, the power of three, the inverse of a power and the power of any given number `a`, respectively.
